### ISSUE TITLE
Reduce Market Creation costs in SOL

### ISSUE THREAD

**Issue by skynetcap** [sayantank/serum-explorer#19]
- Current values are high, order books should evict worst quote at capacity.
- Default creation size should be reduced by a lot, either 1/2 or 1/4.
- Or, at the very least, a slider/toggle/option for the user to choose Market size.

https://github.com/sayantank/serum-explorer/blob/d2c950248ff5b5519c650dbe2b4200d651d6defc/pages/market/create.tsx#L38-L41

Further: https://github.com/project-serum/serum-dex-ui/issues/155

**Comment by sayantank** [comment]
definitely exploring this idea next! thanks for bringing it up @skynetcap !
